In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = [20,10]

In [2]:
df1 = pd.read_csv("Bengaluru_House_Data.csv")
df1.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [3]:
df2 = df1.drop(['area_type', 'society', 'balcony', 'availability'], axis = 'columns')
df2.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [4]:
df2.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [5]:
df3 = df2.dropna()
df3.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [6]:
df3['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [7]:
df3['BHK'] = df3['size'].apply(lambda x: int(x.split(' ')[0]))
df3.head()

/tmp/ipykernel_983/1741794864.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['BHK'] = df3['size'].apply(lambda x: int(x.split(' ')[0]))

                   location       size total_sqft  bath   price  BHK
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [8]:
def is_float(x):
  try:
    float(x)
  except:
    return False
  return True

In [9]:
df3[~df3['total_sqft'].apply(is_float)].head()
# this returns roes where the sqrft is in a range and
# isnt a single value [boolean masking]
# ~ means negation

               location   size   total_sqft  bath    price  BHK
30            Yelahanka  4 BHK  2100 - 2850   4.0  186.000    4
122              Hebbal  4 BHK  3067 - 8156   4.0  477.000    4
137  8th Phase JP Nagar  2 BHK  1042 - 1105   2.0   54.005    2
165            Sarjapur  2 BHK  1145 - 1340   2.0   43.490    2
188            KR Puram  2 BHK  1015 - 1540   2.0   56.800    2

In [10]:
def range_to_val(x):
  tokens = x.split('-')
  if len(tokens) == 2:
    return (float(tokens[0]) + float(tokens[1]))/2
  try:
    return float(x)
  except:
    return None

In [11]:
df4 = df3.copy()
df4['total_sqft'] = df4['total_sqft'].apply(range_to_val)
df4.head()

                   location       size  total_sqft  bath   price  BHK
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [12]:
df4['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [13]:
df5 = df4.copy()
df5['price_per_sqft'] = df5['price']*100000/df5['total_sqft']
df5.head()

,location,size,total_sqft,bath,price,BHK,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000

In [14]:
df5['location'] = df5['location'].apply(lambda x: x.strip())
location_stats = df5.groupby('location')['location'].agg('count').sort_values(ascending = False)
location_stats

location
Whitefield                            535
Sarjapur  Road                        392
Electronic City                       304
Kanakpura Road                        266
Thanisandra                           236
                                     ...
poornaprajna layout                     1
pavitra paradise                        1
near Ramanashree California resort      1
mvj engineering college                 1
1Kasavanhalli                           1
Name: location, Length: 1293, dtype: int64

In [15]:
df5['location'] = df5.location.apply(
    # If the location occurs 10 or fewer times in the dataset, replace it with 'other'
    # Otherwise, keep the original location name
    lambda x: 'other' if x in location_stats[location_stats <= 10] else x
)

# Display the first 10 rows of the updated DataFrame to verify the transformation
df5.head(10)

,location,size,total_sqft,bath,price,BHK,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000
5,Whitefield,2 BHK,1170.0,2.0,38.00,2,3247.863248
6,Old Airport Road,4 BHK,2732.0,4.0,204.00,4,7467.057101
7,Rajaji Nagar,4 BHK,3300.0,4.0,600.00,4,18181.818182
8,Marathahalli,3 BHK,1310.0,3.0,63.25,3,4828.244275
9,other,6 Bedroom,1020.0,6.0,370.00,6,36274.509804

In [16]:
len(df5['location'].unique())

242

In [17]:
df5[(df5['total_sqft']/df5['BHK']) < 300].head()
# these are outliers ar anomalies

,location,size,total_sqft,bath,price,BHK,price_per_sqft
9,other,6 Bedroom,1020.0,6.0,370.0,6,36274.509804
45,HSR Layout,8 Bedroom,600.0,9.0,200.0,8,33333.333333
58,Murugeshpalya,6 Bedroom,1407.0,4.0,150.0,6,10660.980810
68,Devarachikkanahalli,8 Bedroom,1350.0,7.0,85.0,8,6296.296296
70,other,3 Bedroom,500.0,3.0,100.0,3,20000.000000

In [18]:
# We wrap the full comparison in parentheses so that the negation (~) applies to the final boolean result
df6 = df5[~((df5['total_sqft']/df5['BHK']) < 300)]
df6.shape

(12502, 7)

In [19]:
def remove_outliers(df):
  df_out = pd.DataFrame()
  for key, subdf in df.groupby('location'):

    # key: A string representing the name of the current location
    #  (e.g., 'Uttarahalli').
    # subdf: A temporary DataFrame containing only the rows
    #   belonging to that specific location.

    m = np.mean(subdf.price_per_sqft)
    st = np.std(subdf.price_per_sqft)
    reduced_df = subdf[(subdf.price_per_sqft > (m - st)) & (subdf.price_per_sqft <= (m + st))]

    # Filters out the extreme prices (outliers) for this location. It keeps only the
    # rows where the price per sqft is within 1 standard deviation of the mean
    # (between mean - std_dev and mean + std_dev). This keeps roughly 68% of the data points
    #  for each location, filtering out exceptionally cheap or expensive properties

    df_out = pd.concat([df_out, reduced_df], ignore_index = True)
  return df_out

df7 = remove_outliers(df6)
df7.shape
#

(10241, 7)

In [23]:
df8 = df7.drop(['size', 'price_per_sqft'], axis = 'columns')
df8.head(100)

               location  total_sqft  bath  price  BHK
0   1st Block Jayanagar      2850.0   4.0  428.0    4
1   1st Block Jayanagar      1630.0   3.0  194.0    3
2   1st Block Jayanagar      1875.0   2.0  235.0    3
3   1st Block Jayanagar      1200.0   2.0  130.0    3
4   1st Block Jayanagar      1235.0   2.0  148.0    2
..                  ...         ...   ...    ...  ...
95   7th Phase JP Nagar      1175.0   2.0   82.0    2
96   7th Phase JP Nagar      1400.0   2.0   95.0    3
97   7th Phase JP Nagar      2225.0   3.0  160.0    3
98   7th Phase JP Nagar      1050.0   2.0   71.0    2
99   7th Phase JP Nagar      1100.0   2.0   46.0    2

[100 rows x 5 columns]

In [25]:
dummies = pd.get_dummies(df8.location)

In [26]:
df9 = pd.concat([df8, dummies.drop('other', axis = 'columns')], axis = 'columns')
df9.head()

,location,total_sqft,bath,price,BHK,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,1st Block Jayanagar,2850.0,4.0,428.0,4,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1st Block Jayanagar,1630.0,3.0,194.0,3,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1st Block Jayanagar,1875.0,2.0,235.0,3,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1st Block Jayanagar,1200.0,2.0,130.0,3,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1st Block Jayanagar,1235.0,2.0,148.0,2,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [27]:
df10 = df9.drop('location', axis = 'columns')
df10.head()

,total_sqft,bath,price,BHK,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,2850.0,4.0,428.0,4,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1630.0,3.0,194.0,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1875.0,2.0,235.0,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1200.0,2.0,130.0,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1235.0,2.0,148.0,2,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [28]:
X = df10.drop('price', axis = 'columns')
y = df10.price

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)
#

If you don't set random_state (or set it to None), your data will be shuffled differently every single time you run the code. This means you will get different training/testing sets and slightly different model accuracy scores every run.


If you set random_state = 10 (or any other integer), the random shuffling is locked in. Every time you run this cell, you will get the exact same split of training and testing data.

In [30]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(X_train, y_train)
lr_clf.score(X_test, y_test)

0.852067314550884

In [32]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits = 5, test_size = 0.2, random_state = 0)
# n_splits = 5: It will shuffle and split your data 5 separate times
cross_val_score(LinearRegression(), X, y, cv = cv)
#

array([0.77907697, 0.7535079 , 0.79892911, 0.80972959, 0.8025454 ])

Since all 5 scores are fairly close to each other (averaging around 78.8%), it proves that your Linear Regression model is stable and not overly sensitive to how the data is split.

In [39]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
import pandas as pd

def Find_best_model_using_gridsearchcv(X,y):
  algos = {
      'linear_regression': {
          'model': LinearRegression(),
          'params': {}
      },
       'lasso' : {
          'model': Lasso(),
          'params': {
              'alpha': [1, 2],
              'selection': ['random', 'cyclic']
          }
      },
       'decision_tree' : {
          'model': DecisionTreeRegressor(),
          'params': {
              'criterion': ['squared_error', 'friedman_mse'],
              'splitter': ['best', 'random']
          }
      }
  }
  scores = []
  cv = ShuffleSplit(n_splits = 5, test_size = 0.2, random_state =0)
  for algo_name , config in algos.items():
      gs = GridSearchCV(config['model'], config['params'], cv = cv, return_train_score = False)
      gs.fit(X, y)
      scores.append({
          'model': algo_name,
          'best_score': gs.best_score_,
          'best_params': gs.best_params_
      })

  return pd.DataFrame(scores, columns = ['model', 'best_score', 'best_params'])

Find_best_model_using_gridsearchcv(X, y)

,model,best_score,best_params
0,linear_regression,0.788758,{}
1,lasso,0.657015,"{'alpha': 1, 'selection': 'random'}"
2,decision_tree,0.679045,"{'criterion': 'squared_error', 'splitter': 'ra..."

In [40]:
def predict_price(location, sqft, bath, bhk):
  # Create a single-row DataFrame with all 0s, matching the column structure of X
  x = pd.DataFrame(0, index=[0], columns=X.columns)

  # Assign our continuous inputs directly using their column names
  x['total_sqft'] = sqft
  x['bath'] = bath
  x['BHK'] = bhk

  # Safely set the location dummy column to 1 if it exists in the features
  if location in x.columns:
    x[location] = 1

  return lr_clf.predict(x)[0]

1. pd.DataFrame(0, index=[0], columns=X.columns)
pd.DataFrame(...): This is the constructor used to initialize a new pandas DataFrame structure from scratch.
0: The first argument sets the default value for all cells in this newly created DataFrame to 0.
index=[0]: DataFrames are two-dimensional grids with rows and columns. This creates exactly one row, assigning it the index label 0.
columns=X.columns: This passes the list of all column headers from your training set X (all 244 of them).
Syntax Result: You get a $1 \times 244$$1 \times 244$ DataFrame grid of zeroes, where every single column perfectly matches your model's expected features.


x[location] = 1
If the location is found in the columns, we locate that column by its name dynamically and change its value from 0 to 1 (One-hot encoding).

In [44]:
predict_price('1st Phase JP Nagar', 1000, 2, 2)

np.float64(84.57297664209328)

In [46]:
import pickle
with open ('banglore_home_prices_model.pickle', 'wb') as f:
  pickle.dump(lr_clf, f)
#

In [47]:
import json
columns = {
    'data columns' : [col.lower() for col in X.columns]
}
with open('columns.json', 'w') as f:
  f.write(json.dumps(columns))